version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: laravel_app
    restart: always
    volumes:
      - ./:/var/www
    networks:
      - app_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    container_name: laravel_nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
